# Package definition for Jetski Neovim Plugin
package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

filegroup(
    name = "jetski_nvim_files",
    srcs = glob([
        "**/*.lua",
        "**/*.vim",
        "**/*.txt",
        "**/*.md",
    ]),
)
