return {
	"nvim-treesitter/nvim-treesitter",
	event = "VeryLazy",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"lua",
			"toml",
			"cpp",
			"c",
			"python",
			"go",
			"rust",
			"proto",
			"bash",
			"json",
			"yaml",
			"markdown",
			"markdown_inline",
		},
		highlight = { enable = true },
		indent = { enable = true },
	},
  opts_extend = { "ensure_installed" },
}
